apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: user-8wjdk
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.0.203"],"port":8888,"protocol":"TCP","serviceName":"bokeh-demo:bokeh-demo-loadbalancer","allNodes":false}]'
  creationTimestamp: "2020-06-05T07:01:00Z"
  generation: 84
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-bokeh-demo-bokeh-demo
  name: bokeh-demo
  namespace: bokeh-demo
  resourceVersion: "3022077"
  selfLink: /apis/apps/v1/namespaces/bokeh-demo/deployments/bokeh-demo
  uid: 4b914bb9-520d-4964-b907-eee1e56c8a1a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bokeh-demo-bokeh-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-05T19:56:39Z"
        field.cattle.io/ports: '[[{"containerPort":8888,"dnsName":"bokeh-demo-loadbalancer","kind":"LoadBalancer","name":"jupyterlab","protocol":"TCP","sourcePort":8888}]]'
        field.cattle.io/publicEndpoints: '[{"addresses":["192.168.0.203"],"port":8888,"protocol":"TCP","serviceId":"bokeh-demo:bokeh-demo-loadbalancer"}]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-bokeh-demo-bokeh-demo
    spec:
      containers:
      - image: blechritter/kubernetes:bokeh-demo
        imagePullPolicy: IfNotPresent
        name: bokeh-demo
        ports:
        - containerPort: 8888
          name: jupyterlab
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: bokeh-demo-s
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-05T07:01:00Z"
    lastUpdateTime: "2020-06-05T19:56:43Z"
    message: ReplicaSet "bokeh-demo-7cfc8cd97d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-06-06T15:45:18Z"
    lastUpdateTime: "2020-06-06T15:45:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 84
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
