#!/usr/bin/env /bin/sh
pip install anyio
pip install apipkg
pip install appdirs
pip install argon2-cffi
pip install arrow
pip install asn1crypto
pip install attrs
pip install Automat
pip install Babel
pip install backcall
pip install bleach
pip install bokeh
pip install CacheControl
pip install cairocffi
pip install cattrs
pip install certifi
pip install cffi
pip install characteristic
pip install chardet
pip install click
pip install cloudpickle
pip install colorama
pip install colorcet
pip install constantly
pip install contextlib2
pip install cramjam
pip install cryptography
pip install curio
pip install Cython
pip install dask
pip install datashader
pip install datashape
pip install debugpy
pip install decorator
pip install defusedxml
pip install distlib
pip install distributed
pip install distro
pip install django-pipeline
pip install entrypoints
pip install fastparquet
pip install fsspec
pip install HeapDict
pip install holoviews
pip install html5lib
pip install hyperlink
pip install idna
pip install idna-ssl
pip install incremental
pip install ipykernel
pip install ipython
pip install ipython-genutils
pip install ipywidgets
pip install jedi
pip install Jinja2
pip install json5
pip install jsonschema
pip install jupyter-bokeh
pip install jupyter-client
pip install jupyter-core
pip install jupyter-server
pip install jupyterlab
pip install jupyterlab-pygments
pip install jupyterlab-server
pip install jupyterlab-widgets
pip install llvmlite
pip install locket
pip install lockfile
pip install Markdown
pip install MarkupSafe
pip install matplotlib-inline
pip install maturin
pip install mistune
pip install msgpack
pip install multipledispatch
pip install nbclassic
pip install nbclient
pip install nbconvert
pip install nbformat
pip install nest-asyncio
pip install networkx
pip install notebook
pip install numba
pip install numpy
pip install oauthlib
pip install ordered-set
pip install packaging
pip install pandas
pip install pandocfilters
pip install panel
pip install param
pip install parso
pip install partd
pip install pep517
pip install pexpect
pip install pickleshare
pip install Pillow
pip install pip
pip install progress
pip install prometheus-client
pip install prompt-toolkit
pip install psutil
pip install ptyprocess
pip install pyarrow
pip install pyasn1
pip install pyasn1-modules
pip install pycparser
pip install pyct
pip install Pygments
pip install PyHamcrest
pip install pyparsing
pip install pyrsistent
pip install python-dateutil
pip install pytoml
pip install pytz
pip install pyviz-comms
pip install PyYAML
pip install pyzmq
pip install requests
pip install requests-cache
pip install requests-file
pip install requests-futures
pip install requests-mock
pip install requests-oauthlib
pip install requests-toolbelt
pip install requests-unixsocket
pip install retrying
pip install scipy
pip install Send2Trash
pip install service-identity
pip install setuptools
pip install setuptools-scm
pip install six
pip install sniffio
pip install sortedcontainers
pip install tblib
pip install terminado
pip install testpath
pip install thrift
pip install timeout-decorator
pip install toml
pip install toolz
pip install tornado
pip install tqdm
pip install traitlets
pip install Twisted
pip install typing-extensions
pip install url-normalize
pip install urllib3
pip install wcwidth
pip install webencodings
pip install websocket-client
pip install wheel
pip install widgetsnbextension
pip install xarray
pip install zict
pip install zope.interface
NODE_OPTIONS=--max-old-space-size=1024 jupyter labextension install @jupyterlab/geojson-extension
